# Generated by Django 5.1.15 on 2026-02-07 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('catalog_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('right_ascension', models.FloatField(help_text='Right ascension in degrees (0-360)')),
                ('declination', models.FloatField(help_text='Declination in degrees (-90 to +90)')),
                ('distance_parsecs', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('x_parsecs', models.FloatField(blank=True, null=True)),
                ('y_parsecs', models.FloatField(blank=True, null=True)),
                ('z_parsecs', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('morphology', models.CharField(choices=[('spiral', 'Spiral'), ('barred_spiral', 'Barred Spiral'), ('elliptical', 'Elliptical'), ('lenticular', 'Lenticular'), ('irregular', 'Irregular'), ('dwarf_elliptical', 'Dwarf Elliptical'), ('dwarf_spheroidal', 'Dwarf Spheroidal'), ('dwarf_irregular', 'Dwarf Irregular'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('hubble_type', models.CharField(blank=True, default='', help_text='Hubble sequence classification (e.g., Sa, SBb, E3)', max_length=20)),
                ('apparent_magnitude', models.FloatField(blank=True, null=True)),
                ('absolute_magnitude', models.FloatField(blank=True, null=True)),
                ('redshift', models.FloatField(blank=True, null=True)),
                ('angular_size_arcmin', models.FloatField(blank=True, null=True)),
                ('mass_solar', models.FloatField(blank=True, null=True)),
                ('diameter_kpc', models.FloatField(blank=True, null=True)),
                ('num_stars_estimate', models.BigIntegerField(blank=True, null=True)),
                ('galaxy_group', models.CharField(blank=True, default='', max_length=100)),
                ('messier_number', models.CharField(blank=True, default='', max_length=10)),
                ('ngc_number', models.CharField(blank=True, default='', max_length=20)),
                ('ic_number', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'galaxies',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['morphology'], name='gaia_galaxy_morphol_16cdd8_idx'), models.Index(fields=['distance_parsecs'], name='gaia_galaxy_distanc_828928_idx'), models.Index(fields=['apparent_magnitude'], name='gaia_galaxy_apparen_964658_idx')],
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('catalog_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('right_ascension', models.FloatField(help_text='Right ascension in degrees (0-360)')),
                ('declination', models.FloatField(help_text='Declination in degrees (-90 to +90)')),
                ('distance_parsecs', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('x_parsecs', models.FloatField(blank=True, null=True)),
                ('y_parsecs', models.FloatField(blank=True, null=True)),
                ('z_parsecs', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apparent_magnitude', models.FloatField(blank=True, null=True)),
                ('absolute_magnitude', models.FloatField(blank=True, null=True)),
                ('spectral_type', models.CharField(blank=True, default='', help_text='Full spectral classification (e.g., G2V)', max_length=20)),
                ('spectral_class', models.CharField(blank=True, choices=[('O', 'O — Blue, very hot'), ('B', 'B — Blue-white'), ('A', 'A — White'), ('F', 'F — Yellow-white'), ('G', 'G — Yellow (Sun-like)'), ('K', 'K — Orange'), ('M', 'M — Red dwarf'), ('L', 'L — Brown dwarf (cool)'), ('T', 'T — Brown dwarf (methane)'), ('Y', 'Y — Brown dwarf (ultra-cool)')], default='', max_length=2)),
                ('luminosity_solar', models.FloatField(blank=True, null=True)),
                ('mass_solar', models.FloatField(blank=True, null=True)),
                ('radius_solar', models.FloatField(blank=True, null=True)),
                ('temperature_kelvin', models.IntegerField(blank=True, null=True)),
                ('proper_motion_ra', models.FloatField(blank=True, help_text='mas/yr', null=True)),
                ('proper_motion_dec', models.FloatField(blank=True, help_text='mas/yr', null=True)),
                ('radial_velocity', models.FloatField(blank=True, help_text='km/s', null=True)),
                ('hipparcos_id', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('gaia_source_id', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('henry_draper_id', models.CharField(blank=True, default='', max_length=20)),
                ('bayer_designation', models.CharField(blank=True, default='', max_length=50)),
                ('constellation', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['apparent_magnitude'],
                'indexes': [models.Index(fields=['spectral_class'], name='gaia_star_spectra_d24dde_idx'), models.Index(fields=['apparent_magnitude'], name='gaia_star_apparen_afaec5_idx'), models.Index(fields=['distance_parsecs'], name='gaia_star_distanc_e06523_idx')],
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('catalog_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('right_ascension', models.FloatField(help_text='Right ascension in degrees (0-360)')),
                ('declination', models.FloatField(help_text='Declination in degrees (-90 to +90)')),
                ('distance_parsecs', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('x_parsecs', models.FloatField(blank=True, null=True)),
                ('y_parsecs', models.FloatField(blank=True, null=True)),
                ('z_parsecs', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planet_type', models.CharField(choices=[('rocky', 'Rocky / Terrestrial'), ('gas_giant', 'Gas Giant'), ('ice_giant', 'Ice Giant'), ('super_earth', 'Super-Earth'), ('mini_neptune', 'Mini-Neptune'), ('hot_jupiter', 'Hot Jupiter'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('is_exoplanet', models.BooleanField(default=True, help_text='False for Solar System planets, True for exoplanets')),
                ('host_star_name', models.CharField(blank=True, default='', max_length=255)),
                ('mass_jupiter', models.FloatField(blank=True, null=True)),
                ('mass_earth', models.FloatField(blank=True, null=True)),
                ('radius_jupiter', models.FloatField(blank=True, null=True)),
                ('radius_earth', models.FloatField(blank=True, null=True)),
                ('density', models.FloatField(blank=True, help_text='g/cm^3', null=True)),
                ('surface_temperature_kelvin', models.IntegerField(blank=True, null=True)),
                ('orbital_period_days', models.FloatField(blank=True, null=True)),
                ('semi_major_axis_au', models.FloatField(blank=True, null=True)),
                ('eccentricity', models.FloatField(blank=True, null=True)),
                ('inclination_deg', models.FloatField(blank=True, null=True)),
                ('discovery_year', models.IntegerField(blank=True, null=True)),
                ('detection_method', models.CharField(blank=True, choices=[('transit', 'Transit'), ('radial_velocity', 'Radial Velocity'), ('direct_imaging', 'Direct Imaging'), ('microlensing', 'Microlensing'), ('timing', 'Transit Timing Variations'), ('astrometry', 'Astrometry'), ('other', 'Other')], default='', max_length=20)),
                ('host_star', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planets', to='gaia.star')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['planet_type'], name='gaia_planet_planet__ebd42d_idx'), models.Index(fields=['is_exoplanet'], name='gaia_planet_is_exop_6312bb_idx'), models.Index(fields=['distance_parsecs'], name='gaia_planet_distanc_e01a9f_idx')],
            },
        ),
    ]
